// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DebounceController from "./debounce_controller.js"
application.register("debounce", DebounceController)

import DisplayController from "./display_controller.js"
application.register("display", DisplayController)

import RemovalsController from "./removals_controller.js"
application.register("removals", RemovalsController)
